# Example windowrule
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

windowrulev2 = opacity 0.89 override 0.89 override, class:.*

windowrulev2 = workspace special:music, class:feishin|Spotify|Supersonic
windowrulev2 = workspace special:music, initialTitle:Spotify( Free)?  # Spotify wayland, it has no class for some reason
windowrulev2 = workspace special:communication, class:discord|equibop|vesktop|whatsapp

# Picture in picture (resize and move done via script)
windowrulev2 = move 100%-w-2% 100%-w-3%, title:Picture(-| )in(-| )[Pp]icture  # Initial move so window doesn't shoot across the screen from the center
windowrulev2 = keepaspectratio, title:Picture(-| )in(-| )[Pp]icture
windowrulev2 = float, title:Picture(-| )in(-| )[Pp]icture
windowrulev2 = pin, title:Picture(-| )in(-| )[Pp]icture
