# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" ];
    };

  boot.initrd.luks.devices."luks-ssd".device = "/dev/disk/by-uuid/5fafde48-bb53-4379-9d71-db63beb98196";

  fileSystems."/home" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/EFI";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-label/storage";
      fsType = "btrfs";
      options = [ "subvol=@games" "compress=zstd:3" "noatime" "nodatacow" ];
    };

  boot.initrd.luks.devices."luks-hdd".device = "/dev/disk/by-uuid/c7eeaef6-2837-4a83-9e04-c69145463d2b";

  fileSystems."/mnt/snapshots" =
    { device = "/dev/disk/by-label/storage";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-label/storage";
      fsType = "btrfs";
      options = [ "subvol=@storage" "compress=zstd:3" "noatime"];
    };

  swapDevices = [
    {
      device = "/mnt/storage/swap/swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
