{
  imports = [
    ./config-jsonc.nix
    ./style-css.nix
    ./icons/adobe-photoshop-svg.nix
    ./icons/affinity-designer-svg.nix
    ./icons/affinity-photo-svg.nix
    ./icons/affinity-publisher-svg.nix
    ./icons/anki-svg.nix
    ./icons/beekeeper-studio-svg.nix
    ./icons/blender-svg.nix
    ./icons/bruno-svg.nix
    ./icons/calculator-svg.nix
    ./icons/darktable-svg.nix
    ./icons/davinci-resolve-png.nix
    ./icons/dbeaver-svg.nix
    ./icons/discord-svg.nix
    ./icons/docker-svg.nix
    ./icons/excalidraw-png.nix
    ./icons/figma-svg.nix
    ./icons/file-manager-svg.nix
    ./icons/filezilla-svg.nix
    ./icons/firefox-svg.nix
    ./icons/gimp-svg.nix
    ./icons/godot-svg.nix
    ./icons/google-chrome-svg.nix
    ./icons/heroic-svg.nix
    ./icons/inkscape-svg.nix
    ./icons/jetbrains-idea-svg.nix
    ./icons/jetbrains-pycharm-svg.nix
    ./icons/jetbrains-rider-svg.nix
    ./icons/jetbrains-webstorm-svg.nix
    ./icons/krita-svg.nix
    ./icons/lutris-svg.nix
    ./icons/neovim-svg.nix
    ./icons/obsidian-svg.nix
    ./icons/obs-studio-svg.nix
    ./icons/pinta-svg.nix
    ./icons/postman-svg.nix
    ./icons/ryujinx-svg.nix
    ./icons/shotcut-svg.nix
    ./icons/skype-svg.nix
    ./icons/spotify-svg.nix
    ./icons/steam-svg.nix
    ./icons/telegram-svg.nix
    ./icons/terminal-svg.nix
    ./icons/unity-svg.nix
    ./icons/vs-code-svg.nix
    ./icons/whatsapp-svg.nix
    ./icons/wireshark-svg.nix
    ./icons/zed-svg.nix
    ./icons/zen-svg.nix
    ./scripts/adobe_photoshop-sh.nix
    ./scripts/affinity_designer-sh.nix
    ./scripts/affinity_photo-sh.nix
    ./scripts/affinity_publisher-sh.nix
    ./scripts/cheatsheet-py.nix
    ./scripts/reload-sh.nix
    ./styles/_bar-scss.nix
    ./styles/_colours-scss.nix
    ./styles/_dock-scss.nix
    ./styles/index-scss.nix
  ];
}
